[book]
title = "fengxu-blog"
author = "fengxu"
language = "cpp or go or python"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://1708737115.github.io/fengxu-blog"

[preprocessor.foo]
# Add any additional configurations